# GitHub Sponsors configuration for WebOS
# This file enables the "Sponsor" button on the repository

# Instructions:
# 1. Set up GitHub Sponsors at: https://github.com/sponsors
# 2. Uncomment the 'github:' line below and add your username
# 3. Set up any other platforms you want to use (Ko-fi, Patreon, etc.)
# 4. Uncomment those lines and add your usernames
# 5. Commit this file to enable the "Sponsor" button on your repo

# GitHub Sponsors username
# Uncomment and add your GitHub username when you set up GitHub Sponsors:
# github: yanivduke

# Other funding platforms
# Uncomment and add your usernames when you set these up:

# Patreon username
# patreon: webos

# Open Collective username
# open_collective: webos

# Ko-fi username
# ko_fi: webos

# Buy Me a Coffee username
# buy_me_a_coffee: webos

# Liberapay username
# liberapay: webos

# IssueHunt username
# issuehunt: yanivduke

# Custom URLs (up to 4) - PayPal, custom donation pages, etc.
# custom: ['https://paypal.me/yourname']
